auth:
  enabled: false

detectors:
  cpu_detector:
    type: cpu

mqtt:
  enabled: false

detect:
  enabled: false

record:
  enabled: true
  alerts:
    retain:
      days: 1
      mode: motion
  detections:
    retain:
      days: 1
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 14

go2rtc:
  streams:
    URB_KATAPA: rtsp://noc:QYXF84o2@192.168.153.20:554/stream
    MU_CAMBAX: rtsp://noc:QYXF84o2@192.168.184.20:554/stream
    B_4ABRIL_N: rtsp://noc:QYXF84o2@192.168.113.20:554/stream
    BEIRA_ALT2: rtsp://noc:QYXF84o2@192.168.111.20:554/stream
    BR_4ABRIL2: rtsp://noc:QYXF84o2@192.168.112.20:554/stream
    NEGRÃO_S: rtsp://noc:QYXF84o2@192.168.115.20:554/stream
    

cameras:
  URB_KATAPA:
    ffmpeg:
      inputs:
        - path: rtsp://noc:QYXF84o2@192.168.153.20:554/stream
          roles:
            - record
    detect:
      enabled: false

  MU_CAMBAX:
    ffmpeg:
      inputs:
        - path: rtsp://noc:QYXF84o2@192.168.184.20:554/stream
          roles:
            - record
    detect:
      enabled: false

    B_4ABRIL_N:
      ffmpeg:
        inputs:
          - path: rtsp://noc:QYXF84o2@192.168.113.20:554/stream
            roles:
              - record
      detect:
        enabled: false

    BEIRA_ALT2:
      ffmpeg:
        inputs:
          - path: rtsp://noc:QYXF84o2@192.168.111.20:554/stream
            roles:
              - record
      detect:
        enabled: false

    BR_4ABRIL2:
      ffmpeg:
        inputs:
          - path: rtsp://noc:QYXF84o2@192.168.112.20:554/stream
            roles:
              - record
      detect:
        enabled: false

    NEGRÃO_S:
      ffmpeg:
        inputs:
          - path: rtsp://noc:QYXF84o2@192.168.115.20:554/stream
            roles:
              - record
      detect:
        enabled: false

    200_CASAS:
      ffmpeg:
        inputs:
          - path: rtsp://noc:QYXF84o2@192.168.115.20:554/stream
            roles:
              - record
      detect:
        enabled: false